/* Generated by RuntimeBrowser
   Platform: iOS 14.2 (18B92) arm64
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences (5060)
 */
#import <Foundation/Foundation.h>
#import <Preferences/PSSpecifier.h>

@interface PSTextFieldSpecifier : PSSpecifier {
    NSString * _placeholder;
    SEL  bestGuess;
}

- (id)placeholder;
- (void)setPlaceholder:(id)arg1;

@end
